package team006;

public enum ArchonStatus {
		//LOOKING_FOR_DEPOSIT, FIXED_DEPOSIT, MODIFYING_TERRAIN, DEPOSIT_FOUND; //, CAPTURING_DEPOSIT, GATHERING_FLUX;
		LOOKING_FOR_NEAREST_DEPOSIT, LOOKING_FOR_SOME_DEPOSIT, DEPOSIT_FOUND, CAPTURING_DEPOSIT;
}

